### ISSUE TITLE
view more than 5 users/teams

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/partners#22]
I thought we had the ability to view more than the top 5 users/teams. If not we need to add it so you can scroll down the list.

**Comment by smit1678** [comment]
@dalekunce See More functionality is on the Teams. Demo of it [here](http://ds-mm-partner.s3-website-us-east-1.amazonaws.com/many/). 

The challenge for the Users is that it will be a much longer list. I would say that you should use the Leaderboards for viewing more than the top 5 users since they will be much longer than team lists. I think users will have better functionality on the Leaderboards.

**Comment by aawiseman** [comment]
I second what Dale said, would be nice.

**Comment by aawiseman** [comment]
also hi Nate

**Comment by aawiseman** [comment]
How can I get this functionality on my team's site?
